from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

MODELS_DIR = PROJECT_ROOT / "models"
MEDIAPIPE_MODEL_PATH = MODELS_DIR / "holistic_landmarker.task"
HAND_LANDMARKER_MODEL_PATH = MODELS_DIR / "hand_landmarker.task"

DATA_DIR = PROJECT_ROOT / "data"
RAW_VIDEOS_DIR = DATA_DIR / "raw_videos"
PROCESSED_LANDMARKS_DIR = DATA_DIR / "processed_landmarks"
NORMALIZED_LANDMARKS_DIR = DATA_DIR / "normalized_landmarks"

CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints_30"
BEST_CHECKPOINT_PATH = CHECKPOINT_DIR / "best.pt"
LATEST_CHECKPOINT_PATH = CHECKPOINT_DIR / "latest.pt"
LABEL_MAPPING_PATH = CHECKPOINT_DIR / "label_mapping.json"

SEQUENCE_LENGTH = 30
INPUT_FEATURES = 1659

CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30

PROCESS_EVERY_N_FRAMES = 1
PREDICTION_INTERVAL = 3
CONFIDENCE_THRESHOLD = 0.65

TRAIN_EPOCHS = 50
TRAIN_BATCH_SIZE = 4
TRAIN_LR = 0.001
TRAIN_VAL_SPLIT = 0.2
TRAIN_DROPOUT = 0.3
TRAIN_SEED = 42

INSPECT_MIN_SAMPLES = 10
ZERO_RATIO_WARNING_THRESHOLD = 0.90
